#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

#####  ONLY CHANGE THIS BLOCK  ######
PROG=/root/sing-box/sing-box 
RES_DIR=/root/sing-box/ # resource dir / working dir / the dir where you store ip/domain lists
CONF=./config.json   # where is the config file, it can be a relative path to $RES_DIR
#####  ONLY CHANGE THIS BLOCK  ######

start_service() {
  sleep 10 
  procd_open_instance
  procd_set_param command $PROG run -D $RES_DIR -c $CONF

  procd_set_param user root
  procd_set_param limits core="unlimited"
  procd_set_param limits nofile="1000000 1000000"
  procd_set_param stdout 1
  procd_set_param stderr 1
  procd_set_param respawn "${respawn_threshold:-3600}" "${respawn_timeout:-5}" "${respawn_retry:-5}"
  procd_close_instance
  nft add table ip mytable
  nft add chain ip mytable my_singbox '{type filter hook forward priority filter; policy accept;}'
  nft add rule ip mytable my_singbox oifname singtun0 counter accept 
  nft add chain ip mytable my_singbox2 '{type nat hook prerouting priority dstnat; policy accept;}'
  nft add rule ip mytable my_singbox2 udp dport 53 counter redirect to :5333
  nft add rule ip mytable my_singbox2 tcp dport 53 counter redirect to :5333
  echo "sing-box is started!"
}

stop_service() {
  service_stop $PROG
  nft delete table ip mytable
  echo "sing-box is stopped!"
}

reload_service() {
  stop
  sleep 5s
  echo "sing-box is restarted!"
  start
}
